---------------------ARTISTAS-----------------------------
--SELECCIONAR TODOS LOS ARTISTAS
SELECT ID_ARTISTA,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,
NOMBRE_ARTISTICO,GENERO,FECHA_NACIMIENTO,FECHA_CREACION,STATUS,ID_CONTACTO
FROM ARTISTA;

--SELECCIONAR TODOS LOS ARTISTAS CON CONTACTOS, CIUDAD Y PAIS
SELECT AR.ID_ARTISTA, AR.PRIMER_NOMBRE, AR.SEGUNDO_NOMBRE, AR.PRIMER_APELLIDO, AR.SEGUNDO_APELLIDO, AR.NOMBRE_ARTISTICO, AR.GENERO, 
AR.FECHA_NACIMIENTO, AR.FECHA_CREACION, AR.STATUS, CONT.ID_CONTACTO AS CONTACTO, CONT.CELULAR AS CELULAR, CONT.TELEFONO AS TELEFONO,
CONT.DIRECCION AS DIRECCION, CONT.BARRIO AS BARRIO, CONT.EMAIL AS EMAIL, CIU.ID_CIUDAD AS CIUDAD, CIU.NOMBRE AS NOMBRE_CIUDAD,
PA.ID_PAIS AS PAIS, PA.NOMBRE AS NOMBRE_PAIS
FROM ARTISTA AR INNER JOIN CONTACTO CONT
ON AR.ID_CONTACTO = CONT.ID_CONTACTO
INNER JOIN CIUDAD CIU
ON CONT.ID_CIUDAD = CIU.ID_CIUDAD
INNER JOIN PAIS PA
ON CIU.ID_PAIS = PA.ID_PAIS ORDER BY AR.ID_ARTISTA;


--SELECCIONAR UN SOLO ARTISTA
SELECT PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,
NOMBRE_ARTISTICO,GENERO,FECHA_NACIMIENTO,FECHA_CREACION,STATUS,ID_CONTACTO
FROM ARTISTA
WHERE ID_ARTISTA=?;

--CREAR ARTISTA
INSERT INTO ARTISTA (PRIMER_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,
NOMBRE_ARTISTICO,GENERO,FECHA_NACIMIENTO,FECHA_CREACION,STATUS,ID_CONTACTO)
VALUES ('Martin','Garitxen','Mac','Martib Gariix','M',?,?,?,?);

--"ELIMINAR" UN ARTISTA, CAMBIAR EL STATUS
UPDATE ARTISTA
SET STATUS=?
WHERE ID_ARTISTA=?;

--ACTUALIZAR UN ARTISTA
UPDATE ARTISTA
SET PRIMER_NOMBRE=?,SEGUNDO_NOMBRE=?,PRIMER_APELLIDO=?,SEGUNDO_APELLIDO=?,
NOMBRE_ARTISTICO=?,GENERO=?,FECHA_NACIMIENTO=?,FECHA_CREACION=?,STATUS=?,ID_CONTACTO=?
WHERE ID_ARTISTA=?;


---------------------EMPRESAS DIFUSORAS-----------------------------
--SELECCIONAR TODAS LAS EMPRESAS DIFUSORAS
SELECT ID_EMPRESA_DIFUSORA,NOMBRE,FECHA_CREACION,FECHA_TERMINACION,STATUS,
ID_TIPO_ACTIVIDAD, ID_CONTACTO, ID_COSTO_ACTIVIDAD
FROM EMPRESA_DIFUSORA;

--OBTENER EMPRESA DIFUSORA
SELECT ID_EMPRESA_DIFUSORA,NOMBRE,FECHA_CREACION,FECHA_TERMINACION,STATUS,
ID_TIPO_ACTIVIDAD, ID_CONTACTO, ID_COSTO_ACTIVIDAD
FROM EMPRESA_DIFUSORA
WHERE ID_EMPRESA_DIFUSORA=?;
--CREAR EMPRESA DIFUSORA
INSERT INTO EMPRESA_DIFUSORA (NOMBRE,FECHA_CREACION,FECHA_TERMINACION,STATUS,
ID_TIPO_ACTIVIDAD, ID_CONTACTO, ID_COSTO_ACTIVIDAD)
VALUES (?,?,?,?,?,?,?);

--ELIMINAR EMPRESA DIFUSORA
UPDATE EMPRESA_DIFUSORA
SET STATUS=?
WHERE ID_EMPRESA_DIFUSORA=?;
--ACTUALIZAR EMPRESA DIFUSORA 
UPDATE EMPRESA_DIFUSORA
SET NOMBRE=?,FECHA_CREACION=?,FECHA_TERMINACION=?,STATUS=?,
ID_TIPO_ACTIVIDAD=?, ID_CONTACTO=?, ID_COSTO_ACTIVIDAD=?
WHERE ID_EMPRESA_DIFUSORA=?;


---------------------USUARIO-----------------------------
--OBTENER USUARIOS
SELECT ID_USUARIO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,
FECHA_CREACION,STATUS,ID_PERFIL_USUARIO,ID_LOGIN_USUARIO,ID_CONTACTO_USUARIO
FROM USUARIO;
--OBTENER USUARIO
SELECT ID_USUARIO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,
FECHA_CREACION,STATUS,ID_PERFIL_USUARIO,ID_LOGIN_USUARIO,ID_CONTACTO_USUARIO
FROM USUARIO
WHERE ID_USUARIO=?;
--CREAR USUARIO
INSERT INTO USUARIO (PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,
FECHA_CREACION,STATUS,ID_PERFIL_USUARIO,ID_LOGIN_USUARIO,ID_CONTACTO_USUARIO)
VALUES (?,?,?,?,?,?,?,?,?);
--ELIMINAR USUARIO
UPDATE USUARIO
SET STATUS=?
WHERE ID_USUARIO=?;
--ACTUALIZAR USUARIO
UPDATE USUARIO
SET PRIMER_NOMBRE=?,SEGUNDO_NOMBRE=?,PRIMER_APELLIDO=?,SEGUNDO_APELLIDO=?,
FECHA_CREACION=?,STATUS=?,ID_PERFIL_USUARIO=?,ID_LOGIN_USUARIO=?,ID_CONTACTO_USUARIO=?
WHERE ID_USUARIO=?;   

---------------------USUARIO_LOGIN-----------------------------

--OBTENER USUARIO_LOGIN
SELECT ID_USUARIO_LOGIN,NOMBRE_USUARIO,CONTRASENA
FROM USUARIO_LOGIN
WHERE ID_USUARIO_LOGIN=?;
--CREAR USUARIO_LOGIN
INSERT INTO USUARIO_LOGIN (NOMBRE_USUARIO,CONTRASENA)
VALUES (?,?);
--ACTUALIZAR USUARIO_LOGIN
UPDATE USUARIO_LOGIN
SET NOMBRE_USUARIO=?,CONTRASENA=?
WHERE ID_USUARIO_LOGIN=?;

---------------------PERIL-----------------------------

--OBTENER PERFIL
SELECT ID_PERFIL, NOMBRE_PERFIL
FROM PERFIL
WHERE= ID_PERFIL=?;
--CREAR PERFIL
INSERT INTO PERFIL (NOMBRE_PERFIL)
VALUES (?);

---------------------PERMISOS----------------------------------------

--CREAR PERMISO
INSERT INTO PERMISOS (NOMBRE_PERMISO)
VALUES (?);
--ACTUALIZAR PERMISO
UPDATE PERMISO
SET NOMBRE_PERMISO=?
WHERE ID_PERMISO=?;

---------------------PERFIL_PERMISO-----------------------------

--OBTENER PERMISOS_POR_PERFIL
SELECT ID_PERFIL_PERMISO,ID_PERFIL,ID_PERMISO
FROM PERFIL_PERMISO;

--OBTENER PERMISOS DE UN PERFIL
SELECT ID_PERFIL_PERMISO,ID_PERFIL,ID_PERMISO
FROM PERFIL_PERMISO
WHERE ID_PERFIL=?;

---------------------LOG_AUDITORIA-----------------------------

--OBTENER TODOS LOG DE AUDITORIA
SELECT ID_LOG_AUDITORIA,FECHA,HORA,ID_USUARIO_LOG,ID_OPERACION_LOG
FROM LOG_AUDITORIA;
--CREAR LOG DE AUDITORIA
INSERT INTO LOG_AUDITORIA (FECHA,HORA,ID_USUARIO_LOG,ID_OPERACION_LOG)
VALUES (?,?,?,?);

---------------------CONTACTO-----------------------------

--OBTENER CONTACTO
SELECT ID_CONTACTO, CELULAR, TELEFONO, DIRECCION, BARRIO, EMAIL, ID_CIUDAD
FROM CONTACTO
WHERE ID_CONTACTO=?;
--CREAR CONTACTO
INSERT INTO CONTACTO (CELULAR, TELEFONO,
DIRECCION, BARRIO, EMAIL, ID_CIUDAD) VALUES (?,?,?,?,?,?)
--ACTUALIZAR CONTACTO
UPDATE CONTACTO
SET  CELULAR=?, TELEFONO=?, DIRECCION=?, BARRIO=?,  EMAIL=?, ID_CIUDAD=?
WHERE ID_CONTACTO=?
--ULTIMO CONTACTO
SELECT CONTACTO_SEQ.CURRVAL
FROM DUAL;

---------------------CIUDAD-----------------------------

--OBTENER CIUDADES
SELECT ID_CIUDAD, NOMBRE, ID_PAIS 
FROM CIUDAD;
--OBTENER CIUDADES CON PAIS
SELECT CIU.ID_CIUDAD, CIU.NOMBRE AS NOMBRE_CIUDAD, PA.ID_PAIS, PA.NOMBRE AS NOMBRE_PAIS
FROM CIUDAD CIU INNER JOIN PAIS PA
ON CIU.ID_PAIS = PA.ID_PAIS
ORDER BY CIU.ID_CIUDAD;
--OBTENER CIUDAD
SELECT CIU.ID_CIUDAD, CIU.NOMBRE AS NOMBRE_CIUDAD, PA.ID_PAIS, PA.NOMBRE AS NOMBRE_PAIS
FROM CIUDAD CIU INNER JOIN PAIS PA
ON CIU.ID_PAIS = PA.ID_PAIS
WHERE ID_CIUDAD=?;
--CREAR CIUDAD
INSERT INTO CIUDAD (NOMBRE, ID_PAIS)
VALUES (?,?);
--ACTUALIZAR CIUDAD
UPDATE CIUDAD
SET NOMBRE=?, ID_PAIS=?
WHERE ID_CIUDAD=?;

---------------------PAIS-----------------------------
--OBTENER PAISES
SELECT ID_PAIS, NOMBRE
FROM PAIS;
--OBTENER PAIS
SELECT ID_PAIS, NOMBRE
FROM PAIS
WHERE ID_PAIS=?;
--CREAR PAIS
INSERT INTO PAIS (NOMBRE) VALUES (?);
--ACTUALIZAR PAIS
UPDATE PAIS
SET NOMBRE=?
WHERE ID_PAIS=?;